version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - php
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - frontend
    restart: always
    container_name: nginx

  php:
    build: ./php
    volumes:
      - ./www:/var/www/html
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
      - ./php/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./log/php:/var/log/php
    networks:
      - frontend
      - backend
    restart: always
    container_name: php
    cap_add:
      - SYS_PTRACE

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/conf.d/www.cnf:/etc/mysql/conf.d/www.cnf
      - ./log/mysql/mysql_error.log:/var/log/mysql/mysql_error.log
      - ./log/mysql/mysql_general.log:/var/log/mysql/mysql_general.log
      - ./log/mysql/mysql_slow.log:/var/log/mysql/mysql_slow.log
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - TZ=Asia/Shanghai
    networks:
      - backend
    restart: always
    container_name: mysql

  redis:
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/data:/usr/local/redis/data
      - ./log/redis/redis.log:/var/log/redis/redis.log
    networks:
      - backend
    environment:
      - TZ=Asia/Shanghai
    restart: always
    container_name: redis

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
        - PMA_HOST=mysql
        - TZ=Asia/Shanghai
    networks:
      - backend
    container_name: phpmyadmin

  memcached:
    build: ./memcached
    container_name: memcached
    ports:
      - "11211:11211"
    volumes:
      - ./log/memcached/memcached.log/:/tmp/memcached.log
    networks:
      - backend

networks:
  frontend:
  backend:
    
