#记录日志读取位置，防止重启后重复读取
filebeat.registry.path: /etc/registry

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/nginx/access.log
    tags: ["nginx-access"]
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/nginx/error.log
    tags: ["nginx-error"]
    fields_under_root: true

  - type: log
    enabled: true
    paths:
      - /logs/php/php-fpm.access.log
    tags: ["php-access"]
    fields_under_root: true

  - type: log
    enabled: false
    paths:
      - /logs/php/php-fpm.error.log
    tags: ["php-error"]
    fields_under_root: true

  - type: log
    enabled: false
    paths:
      - /logs/php/php-fpm.slow.log
    tags: ["php-slow"]
    fields_under_root: true


# ----------------output.kibana-------------------------
#setup.kibana:
#  host: "localhost:5601"

# ----------------output.elasticsearch-------------------------
#output.elasticsearch:
#  hosts: ["localhost:9200"]
#  protocol: "http"
#  index: "stat_filebeat"
#  # template.name: "stat_ilebeat"
#  # template.path: "filebeat.template.json"
#  # template.overwrite: false

#----------------output.logstash-----------------------------
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

#---------------output.kafka----------------------------------
#output.kafka:
#  enabled: true
#  hosts: ["192.168.10.1:9092","192.168.10.2:9092","192.168.10.3:9092"]
#  topic: "liuzc_test"
#  partition.round_robin:
#    reachable_only: true
#  worker: 2
#  required_acks: 1
#  compression: gzip
#  max_message_bytes: 10000000