global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'main'
    static_configs:
      - targets: ['cadvisor:8080'] #如果是再在同一个docker的networks，应该使用networks内的端口