version: '3.2'

services:
  elasticsearch:
    build:
      context: ./elk/elasticsearch/
      args:
        ELK_VERSION: 7.4.2
    volumes:
      - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elk/elasticsearch/data:/usr/share/elasticsearch/data
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - elk

  logstash:
    build:
      context: ./elk/logstash/
      args:
        ELK_VERSION: 7.4.2
    volumes:
      - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./elk/logstash/pipeline:/usr/share/logstash/pipeline
      - ./elk/logstash/patterns/customize_patterns:/usr/share/logstash/customize_patterns
    container_name: logstash
    ports:
      - "5000:5000"
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - kibana

  kibana:
    build:
      context: ./elk/kibana/
      args:
        ELK_VERSION: 7.4.2
    volumes:
      - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./elk/kibana/entrypoint.sh:/usr/share/kibana/entrypoint.sh
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: ./elk/filebeat/
      args:
        ELK_VERSION: 7.4.2
    user: root
    restart: always
    container_name: filebeat
    command:
      - '-d "*"'
    volumes:
      - ./elk/filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log:/logs:ro
      - ./elk/filebeat/registry:/etc/registry:rw
    networks:
      - elk
    depends_on:
      - logstash

  metricbeat:
    build:
      context: ./elk/metricbeat/
      args:
        ELK_VERSION: 7.5.0
    user: root
    restart: always
    container_name: metricbeat
    volumes:
      - ./elk/metricbeat/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./elk/metricbeat/data:/usr/share/metricbeat/data
    environment:
      - ELASTICSEARCH_HOST='elasticsearch:9200'
      - KIBANA_HOST='kibana:5601'
      - ELASTICSEARCH_USERNAME='elastic'
      - ELASTICSEARCH_PASSWORD='changeme'
    networks:
      - elk
    depends_on:
      - kibana

networks:
  elk:
    driver: bridge
