FROM daocloud.io/library/mysql:latest

#USER root
#
##定义工作目录
#ENV WORK_PATH /usr/mysq
#
##定义sql文件名
#ENV FILE_0 init.sql
#
##将文件拷贝到容器中
#CMD [ "sh", "-c", "touch /usr/mysql" ]
#COPY setup.sh /usr/mysql/setup.sh
#COPY init.sql /usr/mysql/init.sql
#CMD [ "sh", "-c", "chmod -R 777 /usr/mysql && /usr/mysql/setup.sh" ]